-- Data-only migration: every ISO 3166-1 country as a region, with US states and
-- Canadian provinces and territories under their country. Ids are fixed so each
-- path is written out here; reapplying inserts nothing.
INSERT INTO areas (id, parent_id, path, depth, name, name_key, slug, region_code, status, created_at, updated_at) VALUES
('region-ad', NULL, '/region-ad/', 0, 'Andorra', 'andorra', 'andorra', 'AD', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ae', NULL, '/region-ae/', 0, 'United Arab Emirates', 'united-arab-emirates', 'united-arab-emirates', 'AE', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-af', NULL, '/region-af/', 0, 'Afghanistan', 'afghanistan', 'afghanistan', 'AF', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ag', NULL, '/region-ag/', 0, 'Antigua and Barbuda', 'antigua-and-barbuda', 'antigua-and-barbuda', 'AG', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ai', NULL, '/region-ai/', 0, 'Anguilla', 'anguilla', 'anguilla', 'AI', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-al', NULL, '/region-al/', 0, 'Albania', 'albania', 'albania', 'AL', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-am', NULL, '/region-am/', 0, 'Armenia', 'armenia', 'armenia', 'AM', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ao', NULL, '/region-ao/', 0, 'Angola', 'angola', 'angola', 'AO', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-aq', NULL, '/region-aq/', 0, 'Antarctica', 'antarctica', 'antarctica', 'AQ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ar', NULL, '/region-ar/', 0, 'Argentina', 'argentina', 'argentina', 'AR', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-as', NULL, '/region-as/', 0, 'American Samoa', 'american-samoa', 'american-samoa', 'AS', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-at', NULL, '/region-at/', 0, 'Austria', 'austria', 'austria', 'AT', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-au', NULL, '/region-au/', 0, 'Australia', 'australia', 'australia', 'AU', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-aw', NULL, '/region-aw/', 0, 'Aruba', 'aruba', 'aruba', 'AW', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ax', NULL, '/region-ax/', 0, 'Åland Islands', 'aland-islands', 'aland-islands', 'AX', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-az', NULL, '/region-az/', 0, 'Azerbaijan', 'azerbaijan', 'azerbaijan', 'AZ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ba', NULL, '/region-ba/', 0, 'Bosnia and Herzegovina', 'bosnia-and-herzegovina', 'bosnia-and-herzegovina', 'BA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-bb', NULL, '/region-bb/', 0, 'Barbados', 'barbados', 'barbados', 'BB', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-bd', NULL, '/region-bd/', 0, 'Bangladesh', 'bangladesh', 'bangladesh', 'BD', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-be', NULL, '/region-be/', 0, 'Belgium', 'belgium', 'belgium', 'BE', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-bf', NULL, '/region-bf/', 0, 'Burkina Faso', 'burkina-faso', 'burkina-faso', 'BF', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-bg', NULL, '/region-bg/', 0, 'Bulgaria', 'bulgaria', 'bulgaria', 'BG', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-bh', NULL, '/region-bh/', 0, 'Bahrain', 'bahrain', 'bahrain', 'BH', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-bi', NULL, '/region-bi/', 0, 'Burundi', 'burundi', 'burundi', 'BI', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-bj', NULL, '/region-bj/', 0, 'Benin', 'benin', 'benin', 'BJ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-bl', NULL, '/region-bl/', 0, 'Saint Barthélemy', 'saint-barthelemy', 'saint-barthelemy', 'BL', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-bm', NULL, '/region-bm/', 0, 'Bermuda', 'bermuda', 'bermuda', 'BM', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-bn', NULL, '/region-bn/', 0, 'Brunei', 'brunei', 'brunei', 'BN', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-bo', NULL, '/region-bo/', 0, 'Bolivia', 'bolivia', 'bolivia', 'BO', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-bq', NULL, '/region-bq/', 0, 'Caribbean Netherlands', 'caribbean-netherlands', 'caribbean-netherlands', 'BQ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-br', NULL, '/region-br/', 0, 'Brazil', 'brazil', 'brazil', 'BR', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-bs', NULL, '/region-bs/', 0, 'Bahamas', 'bahamas', 'bahamas', 'BS', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-bt', NULL, '/region-bt/', 0, 'Bhutan', 'bhutan', 'bhutan', 'BT', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-bv', NULL, '/region-bv/', 0, 'Bouvet Island', 'bouvet-island', 'bouvet-island', 'BV', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-bw', NULL, '/region-bw/', 0, 'Botswana', 'botswana', 'botswana', 'BW', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-by', NULL, '/region-by/', 0, 'Belarus', 'belarus', 'belarus', 'BY', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-bz', NULL, '/region-bz/', 0, 'Belize', 'belize', 'belize', 'BZ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ca', NULL, '/region-ca/', 0, 'Canada', 'canada', 'canada', 'CA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-cc', NULL, '/region-cc/', 0, 'Cocos (Keeling) Islands', 'cocos-keeling-islands', 'cocos-keeling-islands', 'CC', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-cd', NULL, '/region-cd/', 0, 'Democratic Republic of the Congo', 'democratic-republic-of-the-congo', 'democratic-republic-of-the-congo', 'CD', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-cf', NULL, '/region-cf/', 0, 'Central African Republic', 'central-african-republic', 'central-african-republic', 'CF', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-cg', NULL, '/region-cg/', 0, 'Republic of the Congo', 'republic-of-the-congo', 'republic-of-the-congo', 'CG', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ch', NULL, '/region-ch/', 0, 'Switzerland', 'switzerland', 'switzerland', 'CH', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ci', NULL, '/region-ci/', 0, 'Côte d’Ivoire', 'cote-divoire', 'cote-divoire', 'CI', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ck', NULL, '/region-ck/', 0, 'Cook Islands', 'cook-islands', 'cook-islands', 'CK', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-cl', NULL, '/region-cl/', 0, 'Chile', 'chile', 'chile', 'CL', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-cm', NULL, '/region-cm/', 0, 'Cameroon', 'cameroon', 'cameroon', 'CM', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-cn', NULL, '/region-cn/', 0, 'China', 'china', 'china', 'CN', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-co', NULL, '/region-co/', 0, 'Colombia', 'colombia', 'colombia', 'CO', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-cr', NULL, '/region-cr/', 0, 'Costa Rica', 'costa-rica', 'costa-rica', 'CR', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-cu', NULL, '/region-cu/', 0, 'Cuba', 'cuba', 'cuba', 'CU', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-cv', NULL, '/region-cv/', 0, 'Cape Verde', 'cape-verde', 'cape-verde', 'CV', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-cw', NULL, '/region-cw/', 0, 'Curaçao', 'curacao', 'curacao', 'CW', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-cx', NULL, '/region-cx/', 0, 'Christmas Island', 'christmas-island', 'christmas-island', 'CX', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-cy', NULL, '/region-cy/', 0, 'Cyprus', 'cyprus', 'cyprus', 'CY', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-cz', NULL, '/region-cz/', 0, 'Czechia', 'czechia', 'czechia', 'CZ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-de', NULL, '/region-de/', 0, 'Germany', 'germany', 'germany', 'DE', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-dj', NULL, '/region-dj/', 0, 'Djibouti', 'djibouti', 'djibouti', 'DJ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-dk', NULL, '/region-dk/', 0, 'Denmark', 'denmark', 'denmark', 'DK', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-dm', NULL, '/region-dm/', 0, 'Dominica', 'dominica', 'dominica', 'DM', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-do', NULL, '/region-do/', 0, 'Dominican Republic', 'dominican-republic', 'dominican-republic', 'DO', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-dz', NULL, '/region-dz/', 0, 'Algeria', 'algeria', 'algeria', 'DZ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ec', NULL, '/region-ec/', 0, 'Ecuador', 'ecuador', 'ecuador', 'EC', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ee', NULL, '/region-ee/', 0, 'Estonia', 'estonia', 'estonia', 'EE', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-eg', NULL, '/region-eg/', 0, 'Egypt', 'egypt', 'egypt', 'EG', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-eh', NULL, '/region-eh/', 0, 'Western Sahara', 'western-sahara', 'western-sahara', 'EH', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-er', NULL, '/region-er/', 0, 'Eritrea', 'eritrea', 'eritrea', 'ER', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-es', NULL, '/region-es/', 0, 'Spain', 'spain', 'spain', 'ES', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-et', NULL, '/region-et/', 0, 'Ethiopia', 'ethiopia', 'ethiopia', 'ET', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-fi', NULL, '/region-fi/', 0, 'Finland', 'finland', 'finland', 'FI', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-fj', NULL, '/region-fj/', 0, 'Fiji', 'fiji', 'fiji', 'FJ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-fk', NULL, '/region-fk/', 0, 'Falkland Islands', 'falkland-islands', 'falkland-islands', 'FK', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-fm', NULL, '/region-fm/', 0, 'Micronesia', 'micronesia', 'micronesia', 'FM', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-fo', NULL, '/region-fo/', 0, 'Faroe Islands', 'faroe-islands', 'faroe-islands', 'FO', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-fr', NULL, '/region-fr/', 0, 'France', 'france', 'france', 'FR', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ga', NULL, '/region-ga/', 0, 'Gabon', 'gabon', 'gabon', 'GA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-gb', NULL, '/region-gb/', 0, 'United Kingdom', 'united-kingdom', 'united-kingdom', 'GB', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-gd', NULL, '/region-gd/', 0, 'Grenada', 'grenada', 'grenada', 'GD', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ge', NULL, '/region-ge/', 0, 'Georgia', 'georgia', 'georgia', 'GE', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-gf', NULL, '/region-gf/', 0, 'French Guiana', 'french-guiana', 'french-guiana', 'GF', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-gg', NULL, '/region-gg/', 0, 'Guernsey', 'guernsey', 'guernsey', 'GG', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-gh', NULL, '/region-gh/', 0, 'Ghana', 'ghana', 'ghana', 'GH', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-gi', NULL, '/region-gi/', 0, 'Gibraltar', 'gibraltar', 'gibraltar', 'GI', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-gl', NULL, '/region-gl/', 0, 'Greenland', 'greenland', 'greenland', 'GL', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-gm', NULL, '/region-gm/', 0, 'Gambia', 'gambia', 'gambia', 'GM', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-gn', NULL, '/region-gn/', 0, 'Guinea', 'guinea', 'guinea', 'GN', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-gp', NULL, '/region-gp/', 0, 'Guadeloupe', 'guadeloupe', 'guadeloupe', 'GP', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-gq', NULL, '/region-gq/', 0, 'Equatorial Guinea', 'equatorial-guinea', 'equatorial-guinea', 'GQ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-gr', NULL, '/region-gr/', 0, 'Greece', 'greece', 'greece', 'GR', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-gs', NULL, '/region-gs/', 0, 'South Georgia and South Sandwich Islands', 'south-georgia-and-south-sandwich-islands', 'south-georgia-and-south-sandwich-islands', 'GS', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-gt', NULL, '/region-gt/', 0, 'Guatemala', 'guatemala', 'guatemala', 'GT', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-gu', NULL, '/region-gu/', 0, 'Guam', 'guam', 'guam', 'GU', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-gw', NULL, '/region-gw/', 0, 'Guinea-Bissau', 'guinea-bissau', 'guinea-bissau', 'GW', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-gy', NULL, '/region-gy/', 0, 'Guyana', 'guyana', 'guyana', 'GY', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-hk', NULL, '/region-hk/', 0, 'Hong Kong', 'hong-kong', 'hong-kong', 'HK', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-hm', NULL, '/region-hm/', 0, 'Heard Island and McDonald Islands', 'heard-island-and-mcdonald-islands', 'heard-island-and-mcdonald-islands', 'HM', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-hn', NULL, '/region-hn/', 0, 'Honduras', 'honduras', 'honduras', 'HN', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-hr', NULL, '/region-hr/', 0, 'Croatia', 'croatia', 'croatia', 'HR', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ht', NULL, '/region-ht/', 0, 'Haiti', 'haiti', 'haiti', 'HT', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-hu', NULL, '/region-hu/', 0, 'Hungary', 'hungary', 'hungary', 'HU', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-id', NULL, '/region-id/', 0, 'Indonesia', 'indonesia', 'indonesia', 'ID', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ie', NULL, '/region-ie/', 0, 'Ireland', 'ireland', 'ireland', 'IE', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-il', NULL, '/region-il/', 0, 'Israel', 'israel', 'israel', 'IL', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-im', NULL, '/region-im/', 0, 'Isle of Man', 'isle-of-man', 'isle-of-man', 'IM', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-in', NULL, '/region-in/', 0, 'India', 'india', 'india', 'IN', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-io', NULL, '/region-io/', 0, 'British Indian Ocean Territory', 'british-indian-ocean-territory', 'british-indian-ocean-territory', 'IO', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-iq', NULL, '/region-iq/', 0, 'Iraq', 'iraq', 'iraq', 'IQ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ir', NULL, '/region-ir/', 0, 'Iran', 'iran', 'iran', 'IR', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-is', NULL, '/region-is/', 0, 'Iceland', 'iceland', 'iceland', 'IS', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-it', NULL, '/region-it/', 0, 'Italy', 'italy', 'italy', 'IT', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-je', NULL, '/region-je/', 0, 'Jersey', 'jersey', 'jersey', 'JE', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-jm', NULL, '/region-jm/', 0, 'Jamaica', 'jamaica', 'jamaica', 'JM', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-jo', NULL, '/region-jo/', 0, 'Jordan', 'jordan', 'jordan', 'JO', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-jp', NULL, '/region-jp/', 0, 'Japan', 'japan', 'japan', 'JP', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ke', NULL, '/region-ke/', 0, 'Kenya', 'kenya', 'kenya', 'KE', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-kg', NULL, '/region-kg/', 0, 'Kyrgyzstan', 'kyrgyzstan', 'kyrgyzstan', 'KG', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-kh', NULL, '/region-kh/', 0, 'Cambodia', 'cambodia', 'cambodia', 'KH', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ki', NULL, '/region-ki/', 0, 'Kiribati', 'kiribati', 'kiribati', 'KI', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-km', NULL, '/region-km/', 0, 'Comoros', 'comoros', 'comoros', 'KM', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-kn', NULL, '/region-kn/', 0, 'Saint Kitts and Nevis', 'saint-kitts-and-nevis', 'saint-kitts-and-nevis', 'KN', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-kp', NULL, '/region-kp/', 0, 'North Korea', 'north-korea', 'north-korea', 'KP', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-kr', NULL, '/region-kr/', 0, 'South Korea', 'south-korea', 'south-korea', 'KR', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-kw', NULL, '/region-kw/', 0, 'Kuwait', 'kuwait', 'kuwait', 'KW', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ky', NULL, '/region-ky/', 0, 'Cayman Islands', 'cayman-islands', 'cayman-islands', 'KY', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-kz', NULL, '/region-kz/', 0, 'Kazakhstan', 'kazakhstan', 'kazakhstan', 'KZ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-la', NULL, '/region-la/', 0, 'Laos', 'laos', 'laos', 'LA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-lb', NULL, '/region-lb/', 0, 'Lebanon', 'lebanon', 'lebanon', 'LB', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-lc', NULL, '/region-lc/', 0, 'Saint Lucia', 'saint-lucia', 'saint-lucia', 'LC', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-li', NULL, '/region-li/', 0, 'Liechtenstein', 'liechtenstein', 'liechtenstein', 'LI', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-lk', NULL, '/region-lk/', 0, 'Sri Lanka', 'sri-lanka', 'sri-lanka', 'LK', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-lr', NULL, '/region-lr/', 0, 'Liberia', 'liberia', 'liberia', 'LR', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ls', NULL, '/region-ls/', 0, 'Lesotho', 'lesotho', 'lesotho', 'LS', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-lt', NULL, '/region-lt/', 0, 'Lithuania', 'lithuania', 'lithuania', 'LT', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-lu', NULL, '/region-lu/', 0, 'Luxembourg', 'luxembourg', 'luxembourg', 'LU', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-lv', NULL, '/region-lv/', 0, 'Latvia', 'latvia', 'latvia', 'LV', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ly', NULL, '/region-ly/', 0, 'Libya', 'libya', 'libya', 'LY', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ma', NULL, '/region-ma/', 0, 'Morocco', 'morocco', 'morocco', 'MA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-mc', NULL, '/region-mc/', 0, 'Monaco', 'monaco', 'monaco', 'MC', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-md', NULL, '/region-md/', 0, 'Moldova', 'moldova', 'moldova', 'MD', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-me', NULL, '/region-me/', 0, 'Montenegro', 'montenegro', 'montenegro', 'ME', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-mf', NULL, '/region-mf/', 0, 'Saint Martin', 'saint-martin', 'saint-martin', 'MF', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-mg', NULL, '/region-mg/', 0, 'Madagascar', 'madagascar', 'madagascar', 'MG', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-mh', NULL, '/region-mh/', 0, 'Marshall Islands', 'marshall-islands', 'marshall-islands', 'MH', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-mk', NULL, '/region-mk/', 0, 'North Macedonia', 'north-macedonia', 'north-macedonia', 'MK', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ml', NULL, '/region-ml/', 0, 'Mali', 'mali', 'mali', 'ML', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-mm', NULL, '/region-mm/', 0, 'Myanmar', 'myanmar', 'myanmar', 'MM', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-mn', NULL, '/region-mn/', 0, 'Mongolia', 'mongolia', 'mongolia', 'MN', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-mo', NULL, '/region-mo/', 0, 'Macao', 'macao', 'macao', 'MO', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-mp', NULL, '/region-mp/', 0, 'Northern Mariana Islands', 'northern-mariana-islands', 'northern-mariana-islands', 'MP', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-mq', NULL, '/region-mq/', 0, 'Martinique', 'martinique', 'martinique', 'MQ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-mr', NULL, '/region-mr/', 0, 'Mauritania', 'mauritania', 'mauritania', 'MR', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ms', NULL, '/region-ms/', 0, 'Montserrat', 'montserrat', 'montserrat', 'MS', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-mt', NULL, '/region-mt/', 0, 'Malta', 'malta', 'malta', 'MT', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-mu', NULL, '/region-mu/', 0, 'Mauritius', 'mauritius', 'mauritius', 'MU', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-mv', NULL, '/region-mv/', 0, 'Maldives', 'maldives', 'maldives', 'MV', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-mw', NULL, '/region-mw/', 0, 'Malawi', 'malawi', 'malawi', 'MW', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-mx', NULL, '/region-mx/', 0, 'Mexico', 'mexico', 'mexico', 'MX', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-my', NULL, '/region-my/', 0, 'Malaysia', 'malaysia', 'malaysia', 'MY', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-mz', NULL, '/region-mz/', 0, 'Mozambique', 'mozambique', 'mozambique', 'MZ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-na', NULL, '/region-na/', 0, 'Namibia', 'namibia', 'namibia', 'NA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-nc', NULL, '/region-nc/', 0, 'New Caledonia', 'new-caledonia', 'new-caledonia', 'NC', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ne', NULL, '/region-ne/', 0, 'Niger', 'niger', 'niger', 'NE', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-nf', NULL, '/region-nf/', 0, 'Norfolk Island', 'norfolk-island', 'norfolk-island', 'NF', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ng', NULL, '/region-ng/', 0, 'Nigeria', 'nigeria', 'nigeria', 'NG', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ni', NULL, '/region-ni/', 0, 'Nicaragua', 'nicaragua', 'nicaragua', 'NI', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-nl', NULL, '/region-nl/', 0, 'Netherlands', 'netherlands', 'netherlands', 'NL', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-no', NULL, '/region-no/', 0, 'Norway', 'norway', 'norway', 'NO', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-np', NULL, '/region-np/', 0, 'Nepal', 'nepal', 'nepal', 'NP', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-nr', NULL, '/region-nr/', 0, 'Nauru', 'nauru', 'nauru', 'NR', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-nu', NULL, '/region-nu/', 0, 'Niue', 'niue', 'niue', 'NU', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-nz', NULL, '/region-nz/', 0, 'New Zealand', 'new-zealand', 'new-zealand', 'NZ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-om', NULL, '/region-om/', 0, 'Oman', 'oman', 'oman', 'OM', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-pa', NULL, '/region-pa/', 0, 'Panama', 'panama', 'panama', 'PA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-pe', NULL, '/region-pe/', 0, 'Peru', 'peru', 'peru', 'PE', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-pf', NULL, '/region-pf/', 0, 'French Polynesia', 'french-polynesia', 'french-polynesia', 'PF', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-pg', NULL, '/region-pg/', 0, 'Papua New Guinea', 'papua-new-guinea', 'papua-new-guinea', 'PG', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ph', NULL, '/region-ph/', 0, 'Philippines', 'philippines', 'philippines', 'PH', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-pk', NULL, '/region-pk/', 0, 'Pakistan', 'pakistan', 'pakistan', 'PK', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-pl', NULL, '/region-pl/', 0, 'Poland', 'poland', 'poland', 'PL', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-pm', NULL, '/region-pm/', 0, 'Saint Pierre and Miquelon', 'saint-pierre-and-miquelon', 'saint-pierre-and-miquelon', 'PM', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-pn', NULL, '/region-pn/', 0, 'Pitcairn Islands', 'pitcairn-islands', 'pitcairn-islands', 'PN', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-pr', NULL, '/region-pr/', 0, 'Puerto Rico', 'puerto-rico', 'puerto-rico', 'PR', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ps', NULL, '/region-ps/', 0, 'Palestine', 'palestine', 'palestine', 'PS', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-pt', NULL, '/region-pt/', 0, 'Portugal', 'portugal', 'portugal', 'PT', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-pw', NULL, '/region-pw/', 0, 'Palau', 'palau', 'palau', 'PW', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-py', NULL, '/region-py/', 0, 'Paraguay', 'paraguay', 'paraguay', 'PY', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-qa', NULL, '/region-qa/', 0, 'Qatar', 'qatar', 'qatar', 'QA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-re', NULL, '/region-re/', 0, 'Réunion', 'reunion', 'reunion', 'RE', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ro', NULL, '/region-ro/', 0, 'Romania', 'romania', 'romania', 'RO', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-rs', NULL, '/region-rs/', 0, 'Serbia', 'serbia', 'serbia', 'RS', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ru', NULL, '/region-ru/', 0, 'Russia', 'russia', 'russia', 'RU', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-rw', NULL, '/region-rw/', 0, 'Rwanda', 'rwanda', 'rwanda', 'RW', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-sa', NULL, '/region-sa/', 0, 'Saudi Arabia', 'saudi-arabia', 'saudi-arabia', 'SA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-sb', NULL, '/region-sb/', 0, 'Solomon Islands', 'solomon-islands', 'solomon-islands', 'SB', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-sc', NULL, '/region-sc/', 0, 'Seychelles', 'seychelles', 'seychelles', 'SC', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-sd', NULL, '/region-sd/', 0, 'Sudan', 'sudan', 'sudan', 'SD', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-se', NULL, '/region-se/', 0, 'Sweden', 'sweden', 'sweden', 'SE', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-sg', NULL, '/region-sg/', 0, 'Singapore', 'singapore', 'singapore', 'SG', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-sh', NULL, '/region-sh/', 0, 'Saint Helena', 'saint-helena', 'saint-helena', 'SH', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-si', NULL, '/region-si/', 0, 'Slovenia', 'slovenia', 'slovenia', 'SI', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-sj', NULL, '/region-sj/', 0, 'Svalbard and Jan Mayen', 'svalbard-and-jan-mayen', 'svalbard-and-jan-mayen', 'SJ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-sk', NULL, '/region-sk/', 0, 'Slovakia', 'slovakia', 'slovakia', 'SK', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-sl', NULL, '/region-sl/', 0, 'Sierra Leone', 'sierra-leone', 'sierra-leone', 'SL', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-sm', NULL, '/region-sm/', 0, 'San Marino', 'san-marino', 'san-marino', 'SM', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-sn', NULL, '/region-sn/', 0, 'Senegal', 'senegal', 'senegal', 'SN', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-so', NULL, '/region-so/', 0, 'Somalia', 'somalia', 'somalia', 'SO', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-sr', NULL, '/region-sr/', 0, 'Suriname', 'suriname', 'suriname', 'SR', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ss', NULL, '/region-ss/', 0, 'South Sudan', 'south-sudan', 'south-sudan', 'SS', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-st', NULL, '/region-st/', 0, 'São Tomé and Príncipe', 'sao-tome-and-principe', 'sao-tome-and-principe', 'ST', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-sv', NULL, '/region-sv/', 0, 'El Salvador', 'el-salvador', 'el-salvador', 'SV', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-sx', NULL, '/region-sx/', 0, 'Sint Maarten', 'sint-maarten', 'sint-maarten', 'SX', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-sy', NULL, '/region-sy/', 0, 'Syria', 'syria', 'syria', 'SY', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-sz', NULL, '/region-sz/', 0, 'Eswatini', 'eswatini', 'eswatini', 'SZ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-tc', NULL, '/region-tc/', 0, 'Turks and Caicos Islands', 'turks-and-caicos-islands', 'turks-and-caicos-islands', 'TC', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-td', NULL, '/region-td/', 0, 'Chad', 'chad', 'chad', 'TD', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-tf', NULL, '/region-tf/', 0, 'French Southern Territories', 'french-southern-territories', 'french-southern-territories', 'TF', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-tg', NULL, '/region-tg/', 0, 'Togo', 'togo', 'togo', 'TG', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-th', NULL, '/region-th/', 0, 'Thailand', 'thailand', 'thailand', 'TH', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-tj', NULL, '/region-tj/', 0, 'Tajikistan', 'tajikistan', 'tajikistan', 'TJ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-tk', NULL, '/region-tk/', 0, 'Tokelau', 'tokelau', 'tokelau', 'TK', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-tl', NULL, '/region-tl/', 0, 'Timor-Leste', 'timor-leste', 'timor-leste', 'TL', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-tm', NULL, '/region-tm/', 0, 'Turkmenistan', 'turkmenistan', 'turkmenistan', 'TM', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-tn', NULL, '/region-tn/', 0, 'Tunisia', 'tunisia', 'tunisia', 'TN', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-to', NULL, '/region-to/', 0, 'Tonga', 'tonga', 'tonga', 'TO', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-tr', NULL, '/region-tr/', 0, 'Türkiye', 'turkiye', 'turkiye', 'TR', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-tt', NULL, '/region-tt/', 0, 'Trinidad and Tobago', 'trinidad-and-tobago', 'trinidad-and-tobago', 'TT', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-tv', NULL, '/region-tv/', 0, 'Tuvalu', 'tuvalu', 'tuvalu', 'TV', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-tw', NULL, '/region-tw/', 0, 'Taiwan', 'taiwan', 'taiwan', 'TW', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-tz', NULL, '/region-tz/', 0, 'Tanzania', 'tanzania', 'tanzania', 'TZ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ua', NULL, '/region-ua/', 0, 'Ukraine', 'ukraine', 'ukraine', 'UA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ug', NULL, '/region-ug/', 0, 'Uganda', 'uganda', 'uganda', 'UG', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-um', NULL, '/region-um/', 0, 'United States Minor Outlying Islands', 'united-states-minor-outlying-islands', 'united-states-minor-outlying-islands', 'UM', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us', NULL, '/region-us/', 0, 'United States', 'united-states', 'united-states', 'US', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-uy', NULL, '/region-uy/', 0, 'Uruguay', 'uruguay', 'uruguay', 'UY', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-uz', NULL, '/region-uz/', 0, 'Uzbekistan', 'uzbekistan', 'uzbekistan', 'UZ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-va', NULL, '/region-va/', 0, 'Vatican City', 'vatican-city', 'vatican-city', 'VA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-vc', NULL, '/region-vc/', 0, 'Saint Vincent and the Grenadines', 'saint-vincent-and-the-grenadines', 'saint-vincent-and-the-grenadines', 'VC', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ve', NULL, '/region-ve/', 0, 'Venezuela', 'venezuela', 'venezuela', 'VE', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-vg', NULL, '/region-vg/', 0, 'British Virgin Islands', 'british-virgin-islands', 'british-virgin-islands', 'VG', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-vi', NULL, '/region-vi/', 0, 'United States Virgin Islands', 'united-states-virgin-islands', 'united-states-virgin-islands', 'VI', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-vn', NULL, '/region-vn/', 0, 'Vietnam', 'vietnam', 'vietnam', 'VN', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-vu', NULL, '/region-vu/', 0, 'Vanuatu', 'vanuatu', 'vanuatu', 'VU', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-wf', NULL, '/region-wf/', 0, 'Wallis and Futuna', 'wallis-and-futuna', 'wallis-and-futuna', 'WF', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ws', NULL, '/region-ws/', 0, 'Samoa', 'samoa', 'samoa', 'WS', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ye', NULL, '/region-ye/', 0, 'Yemen', 'yemen', 'yemen', 'YE', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-yt', NULL, '/region-yt/', 0, 'Mayotte', 'mayotte', 'mayotte', 'YT', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-za', NULL, '/region-za/', 0, 'South Africa', 'south-africa', 'south-africa', 'ZA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-zm', NULL, '/region-zm/', 0, 'Zambia', 'zambia', 'zambia', 'ZM', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-zw', NULL, '/region-zw/', 0, 'Zimbabwe', 'zimbabwe', 'zimbabwe', 'ZW', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO areas (id, parent_id, path, depth, name, name_key, slug, region_code, status, created_at, updated_at) VALUES
('region-us-al', 'region-us', '/region-us/region-us-al/', 1, 'Alabama', 'alabama', 'alabama', 'US-AL', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-ak', 'region-us', '/region-us/region-us-ak/', 1, 'Alaska', 'alaska', 'alaska', 'US-AK', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-az', 'region-us', '/region-us/region-us-az/', 1, 'Arizona', 'arizona', 'arizona', 'US-AZ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-ar', 'region-us', '/region-us/region-us-ar/', 1, 'Arkansas', 'arkansas', 'arkansas', 'US-AR', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-ca', 'region-us', '/region-us/region-us-ca/', 1, 'California', 'california', 'california', 'US-CA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-co', 'region-us', '/region-us/region-us-co/', 1, 'Colorado', 'colorado', 'colorado', 'US-CO', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-ct', 'region-us', '/region-us/region-us-ct/', 1, 'Connecticut', 'connecticut', 'connecticut', 'US-CT', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-de', 'region-us', '/region-us/region-us-de/', 1, 'Delaware', 'delaware', 'delaware', 'US-DE', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-dc', 'region-us', '/region-us/region-us-dc/', 1, 'District of Columbia', 'district-of-columbia', 'district-of-columbia', 'US-DC', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-fl', 'region-us', '/region-us/region-us-fl/', 1, 'Florida', 'florida', 'florida', 'US-FL', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-ga', 'region-us', '/region-us/region-us-ga/', 1, 'Georgia', 'georgia', 'georgia-united-states', 'US-GA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-hi', 'region-us', '/region-us/region-us-hi/', 1, 'Hawaii', 'hawaii', 'hawaii', 'US-HI', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-id', 'region-us', '/region-us/region-us-id/', 1, 'Idaho', 'idaho', 'idaho', 'US-ID', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-il', 'region-us', '/region-us/region-us-il/', 1, 'Illinois', 'illinois', 'illinois', 'US-IL', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-in', 'region-us', '/region-us/region-us-in/', 1, 'Indiana', 'indiana', 'indiana', 'US-IN', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-ia', 'region-us', '/region-us/region-us-ia/', 1, 'Iowa', 'iowa', 'iowa', 'US-IA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-ks', 'region-us', '/region-us/region-us-ks/', 1, 'Kansas', 'kansas', 'kansas', 'US-KS', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-ky', 'region-us', '/region-us/region-us-ky/', 1, 'Kentucky', 'kentucky', 'kentucky', 'US-KY', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-la', 'region-us', '/region-us/region-us-la/', 1, 'Louisiana', 'louisiana', 'louisiana', 'US-LA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-me', 'region-us', '/region-us/region-us-me/', 1, 'Maine', 'maine', 'maine', 'US-ME', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-md', 'region-us', '/region-us/region-us-md/', 1, 'Maryland', 'maryland', 'maryland', 'US-MD', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-ma', 'region-us', '/region-us/region-us-ma/', 1, 'Massachusetts', 'massachusetts', 'massachusetts', 'US-MA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-mi', 'region-us', '/region-us/region-us-mi/', 1, 'Michigan', 'michigan', 'michigan', 'US-MI', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-mn', 'region-us', '/region-us/region-us-mn/', 1, 'Minnesota', 'minnesota', 'minnesota', 'US-MN', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-ms', 'region-us', '/region-us/region-us-ms/', 1, 'Mississippi', 'mississippi', 'mississippi', 'US-MS', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-mo', 'region-us', '/region-us/region-us-mo/', 1, 'Missouri', 'missouri', 'missouri', 'US-MO', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-mt', 'region-us', '/region-us/region-us-mt/', 1, 'Montana', 'montana', 'montana', 'US-MT', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-ne', 'region-us', '/region-us/region-us-ne/', 1, 'Nebraska', 'nebraska', 'nebraska', 'US-NE', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-nv', 'region-us', '/region-us/region-us-nv/', 1, 'Nevada', 'nevada', 'nevada', 'US-NV', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-nh', 'region-us', '/region-us/region-us-nh/', 1, 'New Hampshire', 'new-hampshire', 'new-hampshire', 'US-NH', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-nj', 'region-us', '/region-us/region-us-nj/', 1, 'New Jersey', 'new-jersey', 'new-jersey', 'US-NJ', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-nm', 'region-us', '/region-us/region-us-nm/', 1, 'New Mexico', 'new-mexico', 'new-mexico', 'US-NM', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-ny', 'region-us', '/region-us/region-us-ny/', 1, 'New York', 'new-york', 'new-york', 'US-NY', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-nc', 'region-us', '/region-us/region-us-nc/', 1, 'North Carolina', 'north-carolina', 'north-carolina', 'US-NC', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-nd', 'region-us', '/region-us/region-us-nd/', 1, 'North Dakota', 'north-dakota', 'north-dakota', 'US-ND', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-oh', 'region-us', '/region-us/region-us-oh/', 1, 'Ohio', 'ohio', 'ohio', 'US-OH', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-ok', 'region-us', '/region-us/region-us-ok/', 1, 'Oklahoma', 'oklahoma', 'oklahoma', 'US-OK', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-or', 'region-us', '/region-us/region-us-or/', 1, 'Oregon', 'oregon', 'oregon', 'US-OR', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-pa', 'region-us', '/region-us/region-us-pa/', 1, 'Pennsylvania', 'pennsylvania', 'pennsylvania', 'US-PA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-ri', 'region-us', '/region-us/region-us-ri/', 1, 'Rhode Island', 'rhode-island', 'rhode-island', 'US-RI', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-sc', 'region-us', '/region-us/region-us-sc/', 1, 'South Carolina', 'south-carolina', 'south-carolina', 'US-SC', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-sd', 'region-us', '/region-us/region-us-sd/', 1, 'South Dakota', 'south-dakota', 'south-dakota', 'US-SD', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-tn', 'region-us', '/region-us/region-us-tn/', 1, 'Tennessee', 'tennessee', 'tennessee', 'US-TN', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-tx', 'region-us', '/region-us/region-us-tx/', 1, 'Texas', 'texas', 'texas', 'US-TX', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-ut', 'region-us', '/region-us/region-us-ut/', 1, 'Utah', 'utah', 'utah', 'US-UT', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-vt', 'region-us', '/region-us/region-us-vt/', 1, 'Vermont', 'vermont', 'vermont', 'US-VT', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-va', 'region-us', '/region-us/region-us-va/', 1, 'Virginia', 'virginia', 'virginia', 'US-VA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-wa', 'region-us', '/region-us/region-us-wa/', 1, 'Washington', 'washington', 'washington', 'US-WA', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-wv', 'region-us', '/region-us/region-us-wv/', 1, 'West Virginia', 'west-virginia', 'west-virginia', 'US-WV', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-wi', 'region-us', '/region-us/region-us-wi/', 1, 'Wisconsin', 'wisconsin', 'wisconsin', 'US-WI', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-us-wy', 'region-us', '/region-us/region-us-wy/', 1, 'Wyoming', 'wyoming', 'wyoming', 'US-WY', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ca-ab', 'region-ca', '/region-ca/region-ca-ab/', 1, 'Alberta', 'alberta', 'alberta', 'CA-AB', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ca-bc', 'region-ca', '/region-ca/region-ca-bc/', 1, 'British Columbia', 'british-columbia', 'british-columbia', 'CA-BC', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ca-mb', 'region-ca', '/region-ca/region-ca-mb/', 1, 'Manitoba', 'manitoba', 'manitoba', 'CA-MB', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ca-nb', 'region-ca', '/region-ca/region-ca-nb/', 1, 'New Brunswick', 'new-brunswick', 'new-brunswick', 'CA-NB', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ca-nl', 'region-ca', '/region-ca/region-ca-nl/', 1, 'Newfoundland and Labrador', 'newfoundland-and-labrador', 'newfoundland-and-labrador', 'CA-NL', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ca-ns', 'region-ca', '/region-ca/region-ca-ns/', 1, 'Nova Scotia', 'nova-scotia', 'nova-scotia', 'CA-NS', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ca-nt', 'region-ca', '/region-ca/region-ca-nt/', 1, 'Northwest Territories', 'northwest-territories', 'northwest-territories', 'CA-NT', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ca-nu', 'region-ca', '/region-ca/region-ca-nu/', 1, 'Nunavut', 'nunavut', 'nunavut', 'CA-NU', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ca-on', 'region-ca', '/region-ca/region-ca-on/', 1, 'Ontario', 'ontario', 'ontario', 'CA-ON', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ca-pe', 'region-ca', '/region-ca/region-ca-pe/', 1, 'Prince Edward Island', 'prince-edward-island', 'prince-edward-island', 'CA-PE', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ca-qc', 'region-ca', '/region-ca/region-ca-qc/', 1, 'Quebec', 'quebec', 'quebec', 'CA-QC', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ca-sk', 'region-ca', '/region-ca/region-ca-sk/', 1, 'Saskatchewan', 'saskatchewan', 'saskatchewan', 'CA-SK', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
('region-ca-yt', 'region-ca', '/region-ca/region-ca-yt/', 1, 'Yukon', 'yukon', 'yukon', 'CA-YT', 'active', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
ON CONFLICT DO NOTHING;
